name: TReportSystem
main: Teaclon\TReportSystem\Main
version: "2.4.0"
api: 
 - 1.0.0
 - 1.12.0
 - 3.0.0-ALPHA7
 - 3.0.0-ALPHA8
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
 - 3.0.0-ALPHA11
 - 3.0.0-ALPHA12
 - 3.0.0
 - 3.0.1
 - 3.0.4
 - 3.0.6
 - 3.0.7
 - 3.0.8
 - 3.1.0
 - 3.1.1
 - 4.0.0
author: "Teaclon"
load: POSTWORLD
softdepend: ["TSeriesAPI"]



update-message:
 - v1.0.0         插件基础框架编写完成
 - v1.0.0 ~ 2.0.0 添加了邮箱设置, 举报系统雏形, 反馈框架
 - v2.0.1 ~ 2.0.3 完善了举报系统
 - v2.0.4 ~ 2.1.0 测试插件(通过), 修复BUG
 - v2.1.1 ~ 2.2.0 添加了工单系统, 并且测试插件(通过)
 - v2.2.1         完善了指令系统
 - v2.3.0         对接TSAPI, 重写了代码并且规范化
 - v2.4.0         DEBUG上一个版本的遗留问题并且上传至GitHub